# Generated by Django 4.2.23 on 2025-09-06 15:31

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('contactus', '0001_initial'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='About',
            new_name='Contactus',
        ),
    ]
